<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" >
      <meta name="description" content="CesTech Solutions" >
      <meta name="keywords" content="CesTech,homepage" >
      <meta name="author" content="Aniket Debnath 103126828" >
      <title>CesTech Solutions</title>
      <link href="styles/style.css" rel="stylesheet">
	  <script src="scripts/apply.js"></script>
	  <script src="scripts/enhancements.js"></script>
   </head>
   <body id="<?php echo $bodyId; ?>">
      <header>
         <?php include_once 'menu.inc'; ?>
         <?php echo $banner; ?>
      </header>



